// @vitest-environment node
import { it } from "vitest";
import fs from "node:fs";
import { createRequire } from "node:module";
import { loadBook } from "./xlsx-model";
const req = createRequire(import.meta.url);
const fflate = req("C:/Users/RFox/Documents/projects/fe/PRIVATE/solidjs-experimental/node_modules/.pnpm/node_modules/fflate");
const f = "C:/Users/RFox/Documents/docs/reak/testing_flow_2/04_Testing/IR25_S8HR_VoLTE_Testsheet_Telefonica_Germany.xlsm";
it("drawing", async () => {
  const src = new Uint8Array(fs.readFileSync(f));
  const b = (await loadBook(src, "x.xlsm")).book!;
  const out = await b.toBytes();
  const z = fflate.unzipSync(out), zs = fflate.unzipSync(src);
  const names = Object.keys(z).filter(n => /drawing|vml|_rels\/sheet1|ctrlProp|activeX/i.test(n));
  console.log("PARTS saved:", names.join(" | "));
  console.log("PARTS orig :", Object.keys(zs).filter(n => /drawing|vml|_rels\/sheet1|ctrlProp|activeX/i.test(n)).join(" | "));
  const t = fflate.strFromU8(z["xl/drawings/drawing1.xml"]);
  const o = fflate.strFromU8(zs["xl/drawings/drawing1.xml"]);
  console.log("SIZE saved/orig:", t.length, o.length);
  console.log("SAVED head:", t.slice(0, 700));
  const used = new Set([...t.matchAll(/[<\s/]([A-Za-z0-9]+):[A-Za-z]/g)].map(m => m[1]));
  const declared = new Set([...t.matchAll(/xmlns:([A-Za-z0-9]+)=/g)].map(m => m[1]));
  console.log("prefix tanpa deklarasi:", [...used].filter(x => !declared.has(x) && x !== "xml" && x !== "xmlns").join(","));
  console.log("macro attr saved:", (t.match(/macro="[^"]*"/g) ?? []).slice(0, 4).join(","), "| orig:", (o.match(/macro="[^"]*"/g) ?? []).slice(0, 4).join(","));
  const i = t.indexOf("<xdr:sp");
  console.log("SAVED first sp:", i >= 0 ? t.slice(i, i + 1500) : "(tidak ada xdr:sp)");
  console.log("rels saved:", fflate.strFromU8(z["xl/worksheets/_rels/sheet1.xml.rels"] ?? new Uint8Array()).slice(0, 900));
  console.log("rels orig :", fflate.strFromU8(zs["xl/worksheets/_rels/sheet1.xml.rels"] ?? new Uint8Array()).slice(0, 900));
  console.log("drawing rels saved:", fflate.strFromU8(z["xl/drawings/_rels/drawing1.xml.rels"] ?? new Uint8Array()));
}, 120000);
